/* 
 
 Multiplierless multiplication in Z generated from https://spiral.ece.cmu.edu/mcm/gen.html 
 
 Adapted to modular multiplication for Mersenne prime module p = 2^13-1.

 Multiplication by  omega32^3 = (797 8082) = (-7394 -109),
 
 where omega32 = (3077 647), a root of unity of order 32.

*/

/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

`define ADD 1'b0
`define SUB 1'b1

`define ROT1 1
`define ROT2 2
`define ROT3 3
`define ROT4 4
`define ROT9 9

module mrsn_omega32_3_p13 #(
    parameter W = 13
) (
    input logic clk_i,
    input logic rst_ni,
    input logic en_i,
    input logic [W-1:0] x_i,
    output logic [W-1:0] x_c_o,
    output logic [W-1:0] x_s_o
);

  logic [W-1:0] w8, wm7, wm112, wm113, w4, w4_q, w4_qq, wm109, wm3584, wm3584_q, wm3697, x_q;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (~rst_ni) begin
      x_q <= '0;
      w4_q <= '0;
      w4_qq <= '0;
      wm3584_q <= '0;
    end else begin
      if (en_i) begin
        x_q <= x_i;
        w4_q <= w4;
	w4_qq <= w4_q;
        wm3584_q <= wm3584;
      end
    end
  end

  assign w4 = {x_i[W-1-`ROT2 : 0], x_i[W-1 : W-`ROT2]};  //  w4 = w1 << 2;

  assign w8 = {x_i[W-1-`ROT3 : 0], x_i[W-1 : W-`ROT3]};  // w8 = w1 << 3;

  mrsn_add_sub #(
      .N(W)
  ) adder1 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(x_i),
      .b_i(w8),
      .sum_o(wm7)
  );  // wm7 = w1 - w8;



  assign wm112  = {wm7[W-1-`ROT4 : 0], wm7[W-1 : W-`ROT4]};  //    wm112 = wm7 << 4;

  assign wm3584 = {wm7[W-1-`ROT9 : 0], wm7[W-1 : W-`ROT9]};  //  wm3584 = wm7 << 9;

  mrsn_add_sub #(
      .N(W)
  ) adder3 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(wm112),
      .b_i(x_q),
      .sum_o(wm113)
  );  //  wm113 =  wm112 - w1;

  mrsn_add_sub #(
      .N(W)
  ) adder4 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(wm113),
      .b_i(wm3584_q),
      .sum_o(wm3697)
  );  //  wm3697 = wm113 + wm3584;

  mrsn_add_sub #(
      .N(W)
  ) adder5 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(w4_qq),
      .b_i(wm113),
      .sum_o(wm109)
  );  //  wm109 = wm113 + w4;

  assign x_c_o = {wm3697[W-1-`ROT1 : 0], wm3697[W-1 : W-`ROT1]};  //wm7394 = wm3697 << 1;

  assign x_s_o = wm109;

endmodule

