/* 
 
 Multiplierless multiplication in Z generated from https://spiral.ece.cmu.edu/mcm/gen.html 
 
 Adapted to modular multiplication for Mersenne prime module p = 2^19-1.
 
 Multiplication by omega16 = (162504   42613) = (162504 -481674), a root of unity of order 16.
 
*/

/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

`define ADD 1'b0
`define SUB 1'b1

`define ROT1 1
`define ROT2 2
`define ROT3 3
`define ROT4 4
`define ROT6 6
`define ROT9 9
`define ROT12 12


module mrsn_omega16_p19 #(
    parameter W = 19
) (
    input logic clk_i,
    input logic rst_ni,
    input logic en_i,
    input logic [W-1:0] x_i,
    output logic [W-1:0] x_c_o,
    output logic [W-1:0] x_s_o
);


  logic [W-1:0]	 w4, w5, w20480, w20475, w80, w81, w162, w20313, w512, w511;
 
  logic [W-1:0] x_q, w4088, w4083, w261312, wm240837, w162504, w481674;


  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (~rst_ni) begin
      x_q <= '0;
    end else begin
      if (en_i) begin
        x_q <= x_i;
      end
    end
  end

  //Stage 1			 

  assign w4   = {x_i[W-1-`ROT2 : 0], x_i[W-1 : W-`ROT2]};  // w4 = w1 << 2;

  assign w512 = {x_i[W-1-`ROT9 : 0], x_i[W-1 : W-`ROT9]};  // w512 = w1 << 9;

  mrsn_add_sub #(
      .N(W)
  ) adder1 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(x_i),
      .b_i(w4),
      .sum_o(w5)
  );  // w5 = w1 + w4;

  mrsn_add_sub #(
      .N(W)
  ) adder2 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w512),
      .b_i(x_i),
      .sum_o(w511)
  );  // w511 = w512 - w1;


  //Stage 2

  assign w20480 = {w5[W-1-`ROT12 : 0], w5[W-1 : W-`ROT12]}; // w20480 = w5 << 12;

  assign w80    = {w5[W-1-`ROT4 : 0], w5[W-1 : W-`ROT4]}; // w80 = w5 << 4;

  assign w4088   = {w511[W-1-`ROT3 : 0], w511[W-1 : W-`ROT3]}; // w4088 = w511 << 3;

  mrsn_add_sub #(
      .N(W)
  ) adder3 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w20480),
      .b_i(w5),
      .sum_o(w20475)
  );  // w20475 = w20480 - w5;

  mrsn_add_sub #(
      .N(W)
  ) adder4 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(x_q),
      .b_i(w80),
      .sum_o(w81)
  );  // w81 = x_q + w80;

  mrsn_add_sub #(
      .N(W)
  ) adder5 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w4088),
      .b_i(w5),
      .sum_o(w4083)
  );  // w4083 = w4088 - w5;


  //Stage 3

  assign w162    = {w81[W-1-`ROT1 : 0], w81[W-1 : W-`ROT1]}; // w162 = w81 << 1;

  assign w261312 = {w4083[W-1-`ROT6 : 0], w4083[W-1 : W-`ROT6]}; // w261312 = w4083 << 6;

  mrsn_add_sub #(
      .N(W)
  ) adder6 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w20475),
      .b_i(w162),
      .sum_o(w20313)
  );  // w20313 = w20475 - w162;  

  mrsn_add_sub #(
      .N(W)
  ) adder7 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w20475),
      .b_i(w261312),
      .sum_o(wm240837)
  );  // wm240837 = w20475 - w261312 ;


  assign x_c_o = {w20313[W-1-`ROT3 : 0], w20313[W-1 : W-`ROT3]};  // w162504 = w20313 << 3;

  assign x_s_o = {wm240837[W-1-`ROT1 : 0], wm240837[W-1 : W-`ROT1]};  // wm481674 = wm240837 << 1;

endmodule


