/* 
 
 Multiplierless multiplication in Z generated from https://spiral.ece.cmu.edu/mcm/gen.html 
 
 Adapted to modular multiplication for Mersenne prime module p = 2^19-1.
 
 Multiplication by omega32^3 = (386366   62144) = (-137921  62144) 

*/

/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */


`define ADD 1'b0
`define SUB 1'b1

`define ROT2 2
`define ROT4 4
`define ROT5 5
`define ROT6 6
`define ROT7 7



module mrsn_omega32_3_p19 #(
    parameter W = 19
) (
    input logic clk_i,
    input logic rst_ni,
    input logic en_i,
    input logic [W-1:0] x_i,
    output logic [W-1:0] x_c_o,
    output logic [W-1:0] x_s_o
);



  logic [W-1:0] w16, w15, w128, w127, w8128, wm8113, wm129808, wm137921;

   logic [W-1:0] w4, w4_q, wm11, w960, w960_q, w971;
   



  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (~rst_ni) begin
      w4_q   <= '0;
      w960_q <= '0;
    end else begin
      if (en_i) begin
        w4_q   <= w4;
        w960_q <= w960;
      end
    end
  end


  assign w4   = {x_i[W-1-`ROT2 : 0], x_i[W-1 : W-`ROT2]};  //w4 = w1 << 2;

  assign w16  = {x_i[W-1-`ROT4 : 0], x_i[W-1 : W-`ROT4]};  // w16   = w1 << 4;

  assign w128 = {x_i[W-1-`ROT7 : 0], x_i[W-1 : W-`ROT7]};  // w128 = w1 << 7;


  mrsn_add_sub #(
      .N(W)
  ) adder1 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w16),
      .b_i(x_i),
      .sum_o(w15)
  );  // w15 = w16 - w1;

  mrsn_add_sub #(
      .N(W)
  ) adder2 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w128),
      .b_i(x_i),
      .sum_o(w127)
  );  // w127 = w128 - w1;


  assign w8128 = {w127[W-1-`ROT6 : 0], w127[W-1 : W-`ROT6]};  //w8128 = w127 << 6;

  assign w960  = {w15[W-1-`ROT6 : 0], w15[W-1 : W-`ROT6]};  //w960 = w15 << 6;


  mrsn_add_sub #(
      .N(W)
  ) adder3 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w15),
      .b_i(w8128),
      .sum_o(wm8113)
  );  //wm8113 = -w8128 + w15;
  mrsn_add_sub #(
      .N(W)
  ) adder4 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w4_q),
      .b_i(w15),
      .sum_o(wm11)
  );  // wm11 = - w15 + w4;

  assign wm129808 = {wm8113[W-1-`ROT4 : 0], wm8113[W-1 : W-`ROT4]};  //wm129808 = wm8113 << 4;

  mrsn_add_sub #(
      .N(W)
  ) adder5 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(wm8113),
      .b_i(wm129808),
      .sum_o(wm137921)
  );  // wm137921 = wm8113 + wm129808;

  mrsn_add_sub #(
      .N(W)
  ) adder6 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w960_q),
      .b_i(wm11),
      .sum_o(w971)
  );  //w971 =  w960 - wm11;

  assign x_c_o = wm137921;

  assign x_s_o = {w971[W-1-`ROT6 : 0], w971[W-1 : W-`ROT6]};  // w62144 = w971 << 6;

endmodule

