/* 
 
 Multiplierless multiplication in Z generated from https://spiral.ece.cmu.edu/mcm/gen.html 
 
 Adapted to modular multiplication for Mersenne prime module p = 2^13-1.

 Multiplication by omega32 = (3077   647), a root of unity of order 32.
 
*/

/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */


`define ADD 1'b0
`define SUB 1'b1

`define ROT2 2
`define ROT3 3
`define ROT7 7
`define ROT10 10


module mrsn_omega32_p13 #(
    parameter W = 13
) (
    input logic clk_i,
    input logic rst_ni,
    input logic en_i,
    input logic [W-1:0] x_i,
    output logic [W-1:0] x_c_o,
    output logic [W-1:0] x_s_o
);

  logic [W-1:0] w4, w5, w3, w3072, w3077, w8, w7, w640, w647;

  assign w4 = {x_i[W-1-`ROT2 : 0], x_i[W-1 : W-`ROT2]};  //  w4 = w1 << 2;

  assign w8 = {x_i[W-1-`ROT3 : 0], x_i[W-1 : W-`ROT3]};  // w8 = w1 << 3;

  mrsn_add_sub #(
      .N(W)
  ) adder1 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(w4),
      .b_i(x_i),
      .sum_o(w5)
  );  //w5 = w1 + w4;
 
  mrsn_add_sub #(
      .N(W)
  ) adder2 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w4),
      .b_i(x_i),
      .sum_o(w3)
  );  //w3 = w4 - w1;
  
  mrsn_add_sub #(
      .N(W)
  ) adder3 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w8),
      .b_i(x_i),
      .sum_o(w7)
  );  //w7 = w8 - w1;

  assign w3072 = {w3[W-1-`ROT10 : 0], w3[W-1 : W-`ROT10]};  // w3072 = w3 << 10;

  assign w640  = {w5[W-1-`ROT7 : 0], w5[W-1 : W-`ROT7]};  // w640 = w5 << 7;

  mrsn_add_sub #(
      .N(W)
  ) adder4 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(w5),
      .b_i(w3072),
      .sum_o(w3077)
  );  // w3077 = w5 + w3072;

  mrsn_add_sub #(
      .N(W)
  ) adder5 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(w7),
      .b_i(w640),
      .sum_o(w647)
  );  //  w647 = w7 + w640;

  //Add a cycle to have uniform delay for all multiplierless operations (total of 3 cycles)

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (~rst_ni) begin
      x_c_o <= '0;
      x_s_o <= '0;
    end else begin
      if (en_i) begin
        x_c_o <= w3077;
        x_s_o <= w647;
      end
    end
  end

endmodule
