/* 
 
 Multiplierless multiplication in Z generated from https://spiral.ece.cmu.edu/mcm/gen.html 
 
 Adapted to modular multiplication for Mersenne prime module p = 2^13-1.

 Multiplication by omega16 = (6456 812), a root of unity of order 16.
 
*/

/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

`define ADD 1'b0
`define SUB 1'b1

`define ROT1 1
`define ROT2 2
`define ROT3 3
`define ROT5 5
`define ROT10 10

module mrsn_omega16_p13 #(
    parameter W = 13
) (
    input logic clk_i,
    input logic rst_ni,
    input logic en_i,
    input logic [W-1:0] x_i,
    output logic [W-1:0] x_c_o,
    output logic [W-1:0] x_s_o
);



  logic [W-1:0] w8, w1024, w1024_q, w1024_qq, w7, w224, w14, w14_q, w217, w807, w203;


  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (~rst_ni) begin
      w1024_q  <= '0;
      w1024_qq <= '0;
      w14_q    <= '0;
    end else begin
      if (en_i) begin
        w1024_q  <= w1024;
        w1024_qq <= w1024_q;
        w14_q    <= w14;
      end
    end
  end  // always_ff @ (posedge clk_i or negedge rst_ni)


  assign w8 = {x_i[W-1-`ROT3 : 0], x_i[W-1 : W-`ROT3]};

  assign w1024 = {x_i[W-1-`ROT10 : 0], x_i[W-1 : W-`ROT10]};

  mrsn_add_sub #(
      .N(W)
  ) adder1 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w8),
      .b_i(x_i),
      .sum_o(w7)
  );

  assign w224 = {w7[W-1-`ROT5 : 0], w7[W-1 : W-`ROT5]};

  assign w14  = {w7[W-1-`ROT1 : 0], w7[W-1 : W-`ROT1]};

  mrsn_add_sub #(
      .N(W)
  ) adder2 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w224),
      .b_i(w7),
      .sum_o(w217)
  );

  mrsn_add_sub #(
      .N(W)
  ) adder3 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w1024_qq),
      .b_i(w217),
      .sum_o(w807)
  );

  mrsn_add_sub #(
      .N(W)
  ) adder4 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w217),
      .b_i(w14_q),
      .sum_o(w203)
  );


  assign x_c_o = {w807[W-1-`ROT3 : 0], w807[W-1 : W-`ROT3]};

  assign x_s_o = {w203[W-1-`ROT2 : 0], w203[W-1 : W-`ROT2]};

endmodule
