/* 
 
 Multiplierless multiplication in Z generated from https://spiral.ece.cmu.edu/mcm/gen.html 
 
 Adapted to modular multiplication for Mersenne prime module p = 2^19-1.
 
 Multiplication by omega32 (523701  326972) =  (-586  -197315),  a root of unity of order 32.

*/

/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */


`define ADD 1'b0
`define SUB 1'b1

`define ROT1 1
`define ROT2 2
`define ROT3 3
`define ROT5 5
`define ROT6 6
`define ROT7 7
`define ROT14 14

module mrsn_omega32_p19 #(
    parameter W = 19
) (
    input logic clk_i,
    input logic rst_ni,
    input logic en_i,
    input logic [W-1:0] x_i,
    output logic [W-1:0] x_c_o,
    output logic [W-1:0] x_s_o
);


  logic [W-1:0]	 w64, w65, w260, w325, w32, w32_q, w32_qq;
   
  logic [W-1:0] wm293, w16384, w16385, w8320, w24705, w197640, wm197315;


  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (~rst_ni) begin
      w32_q  <= '0;
      w32_qq <= '0;
    end else begin
      if (en_i) begin
        w32_q  <= w32;
        w32_qq <= w32_q;
      end
    end
  end


  assign w32    = {x_i[W-1-`ROT5 : 0],  x_i[W-1 : W-`ROT5]};//   w32 = w1 << 5;

  assign w64    = {x_i[W-1-`ROT6 : 0],  x_i[W-1 : W-`ROT6]};//   w64 = w1 << 6;

  assign w16384 = {x_i[W-1-`ROT14 : 0], x_i[W-1 : W-`ROT14]}; // w16384 = w1 << 14;


  mrsn_add_sub #(
      .N(W)
  ) adder1 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(x_i),
      .b_i(w64),
      .sum_o(w65)
  );  // w65 = w1 + w64;

  mrsn_add_sub #(
      .N(W)
  ) adder2 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(x_i),
      .b_i(w16384),
      .sum_o(w16385)
  );  // w16385 = w1 + w16384;

  assign w260  = {w65[W-1-`ROT2 : 0], w65[W-1 : W-`ROT2]};  //  w260 = w65 << 2;

  assign w8320 = {w65[W-1-`ROT7 : 0], w65[W-1 : W-`ROT7]};  //  w8320 = w65 << 7;

  mrsn_add_sub #(
      .N(W)
  ) adder3 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(w65),
      .b_i(w260),
      .sum_o(w325)
  );  // w325 = w65 + w260;

  mrsn_add_sub #(
      .N(W)
  ) adder4 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`ADD),
      .a_i(w16385),
      .b_i(w8320),
      .sum_o(w24705)
  );  // w24705 = w16385 + w8320;

  assign w197640 = {w24705[W-1-`ROT3 : 0], w24705[W-1 : W-`ROT3]};  //w197640 = w24705 << 3;

  mrsn_add_sub #(
      .N(W)
  ) adder5 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w32_qq),
      .b_i(w325),
      .sum_o(wm293)
  );  //wm293 = - w325 + w32;

  mrsn_add_sub #(
      .N(W)
  ) adder6 (
      .clk_i(clk_i),
      .rst_ni(rst_ni),
      .en_i(en_i),
      .mode_i(`SUB),
      .a_i(w325),
      .b_i(w197640),
      .sum_o(wm197315)
  );  // wm197315 = - w197640 + w325;

  assign x_c_o = {wm293[W-1-`ROT1 : 0], wm293[W-1 : W-`ROT1]};  //wm586 = wm293 << 1;

  assign x_s_o = wm197315;

endmodule

